### ISSUE TITLE
Unused field `fee`

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#31]
Not super important, but anyway. 

In structure `DepositedEvent` we have a field `fee` https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/deposit_event.rs#L240

This structure is used only in one place: https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/connector_impl.rs#L96 and the field `fee` is never used. For Aurora transaction this value is stored in TokenMessageData.

So, we can just remove the `fee` field from the `DepositedEvent`.

**Comment by mrLSD** [comment]
Make sense.

**Comment by mrLSD** [comment]
Fixed in #36
