### ISSUE TITLE
Style fix: reorder args in WithdrawResult

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#34]
I propose to reorder the arguments in `WithdrawResult` here: 
* https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L504
* https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L531

To make it consistent with: 
https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/connector_impl.rs#L42

**Comment by mrLSD** [comment]
Implemented with #52
