### ISSUE TITLE
Using `LookupMap` instead `LookupSet` for `used_proofs`

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#39]
For storing `used_proofs` in `EthConnectorContract` currently the `LookupMap` is used. However only `true` value is stored to this map and the value is never checked. 

So, it makes sense to change `LookupMap` into `LookupSet`: https://docs.rs/near-sdk/latest/near_sdk/collections/struct.LookupSet.html

**Comment by mrLSD** [comment]
Refactored at #50
