### ISSUE TITLE
Lack of gas check in `internal_ft_transfer_call`

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#40]
In the original implementation of the `ft_transfer_call` the amount of gas is checked at the beginning: https://docs.rs/near-contract-standards/latest/src/near_contract_standards/fungible_token/core_impl.rs.html#136

In our implementation, there is no such check: https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L110

Also, the `GAS_FOR_FT_TRANSFER_CALL` is the same as in the original implementation, but we execute more operations and it looks like we should consume more gas. But if gas is taken into account with some margin, i think everything is ok. 

And I have just noticed, that the Near docs contain the wrong implementation of the `ft_transfer_call` from that point of view: https://docs.near.org/tutorials/fts/transfers#transfer-call-function

**Comment by mrLSD** [comment]
Seems the problem was related to an issue with the reference example. Thanks.

**Comment by mrLSD** [comment]
Refactored at #51
