### ISSUE TITLE
Unnecessary Initialization verification

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#43]
No need for check `require!(!env::state_exists(), "Already initialized");`. It is already checked in `#[init]` macro. 

https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L173

Commit in near_sdk where the behavior has been changed: 
https://github.com/near/near-sdk-rs/commit/18b8f8f3b672bfb422ff83a5138395f7e24dd70d

**Comment by mrLSD** [comment]
@olga24912  Proof?

**Comment by mrLSD** [comment]
#53

**Comment by mrLSD** [comment]
Refactored at #53
