### ISSUE TITLE
Why we need default `metadata`?

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#45]
`EthConnectorContract` panic on default and in `new` function we always should provide `metadata`. It is no way that `metadata` was not initialized. 

Why we have a default value in `ft_metadata` in that case?
https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L437

**Comment by mrLSD** [comment]
For tests case. It's good to know default data for the Metadata stucture for tests flow. I can't see any problems/issue with that, because as you mentioned we do not use it in the contract itself.
