### ISSUE TITLE
Lack of  `accounts_counter` inc/dec

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#46]
`accounts_counter` indicates the amount of registered account: https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L59

It is incremented only in `register_if_nor_exists` function: https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L97

But if we register new account by calling `storage_deposit` the `account_counter` will not be incremented: https://docs.rs/near-contract-standards/latest/src/near_contract_standards/fungible_token/storage_impl.rs.html#45

Also, it will not be decremented if we call `storage_unregister`.

**Comment by mrLSD** [comment]
Refactored at #56
