### ISSUE TITLE
Field order in `FtTransferMessageData`

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#48]
Super minor. I propose to reorder fields in `FtTransferMessageData` in following order
```
pub struct FtTransferMessageData {
    pub relayer: AccountId,
    pub fee: Fee,
   pub recipient: Address,
}
```

Due to being consistent with the serialization format, which is <relayer_account_id>:<fee><recipient>

https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/deposit_event.rs#L21

**Comment by mrLSD** [comment]
Implemented with #52
