### ISSUE TITLE
Conflict during migration with data in the contract

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#49]
Do I understand correctly the migration mechanism: 
* First we create and init contract
* Migrate the data

In that case, we already have some data in the contract. For example, we register the `current_account_id` and `owner_id` and change `accounts_counter` https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L197

After migration, we don't delete the current_account_id and owner_id from the accounts list, but rewrite `account_counter`, as a result, it can become incorrect.  https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L625

Moreover, we don't check at the end of the migration that the data is consistent: 
* account_counter == self.ft.account.size();
* ft.total_supply == sum(ft.accounts.amount)
* ft.account_storage_usage == ???

And we don't migrate `metadata`

I propose checking before migration that all the data is empty and don't register anything in `new` function. 

Or presenting more clear guarantee for the migration. For example, merge the data instead of rewriting it.

**Comment by mrLSD** [comment]
I think it's one major mistake here. Data should be the same as migrated data from the Engine. It means:
1. ft.total_supply == total_supply from migration
2. ft.accounts != accounts count from migration. But all accounts from migration  should exist in `eth-connector`
3. ft.account_counter > self.ft.account.size();

But about `account_counter` field. May be good idea just recalculate it, yes.

Other data look consistent, and checked with method `check_migration_correctness`

**Comment by mrLSD** [comment]
We shouldn't migrate metadata. It's constant data, and it's initialized with contract.

**Comment by mrLSD** [comment]
Refactored at #56
